# settings alerts
alertconfig:
 alerts:

  - if: "SELECT tc.name, AVG(tc.cpu_use)
         FROM cpu_use AS tc
         WHERE tc.timestamp > {{sub .TimestampSec (mul 60 60)}}
         GROUP BY tc.name
         HAVING AVG(tc.cpu_use) > 0.7"
    then: "warning avg cpu: {{.V2}} in server: {{.V1}}"
    else: ""

  - if: "SELECT tm.name, AVG(tm.memory_use)
         FROM memory_use AS tm
         WHERE tm.timestamp > {{sub .TimestampSec (mul 60 60)}}
         GROUP BY tm.name
         HAVING AVG(tm.memory_use) > {{mul 50 1024}}"
    then: "warning avg memory: {{.V2}} in server: {{.V1}}"
    else: ""

 pushers: [ telegram ]
 checkeveryseconds: 360
 checkconnservereveryseconds: 180
 dataconnects: /Users/peterkorotkiy/go/src/github.com/darkfoxs96/servermetric/connects-data.cfg

# telegram, email ... Now supported only 'telegram bot'
pushers:
 telegram:
  token: "841563697:AAEDpNQBkNpFSUtae_ZgSRhxKzeJRntdrik"
  data: /Users/peterkorotkiy/go/src/github.com/darkfoxs96/servermetric/telegram-data.cfg

# params for connect to clickhouse
database:
  username: "clickhouse"
  password: "clickhouse"
  database: "default"
  host: "localhost"
  port: "9001"

# create table by metrics
metrics:
  cpu_use:
    timestamp: "Int64 DEFAULT 0" # In seconds
    cpu_use: "Float64 DEFAULT 0.0" # 0.63
    name: "String DEFAULT ''" # https://site.com/1
  memory_use:
    timestamp: "Int64 DEFAULT 0" # In seconds
    memory_use: "Int64 DEFAULT 0" # KB
    all_memory: "Int64 DEFAULT 0" # KB
    name: "String DEFAULT ''" # https://site2.com/3

# server settings
server:
  port: "9082"
  key: "SDDEDpNQBkNpFSUtae_ZgSRhxKzeJRntdrik"
