# settings alerts
alertconfig:
 alerts:

  - if: "SELECT tc.name, AVG(tc.cpu_use)
         FROM cpu_use AS tc
         WHERE tc.event_datetime > subtractHours(NOW(), 1)
         GROUP BY tc.name
         HAVING AVG(tc.cpu_use) > 0.7"
    then: "warning avg cpu: {{.V2}} in server: {{.V1}}"
    else: ""

  - if: "SELECT tm.name, AVG(tm.memory_use)
         FROM memory_use AS tm
         WHERE tm.event_datetime > subtractHours(NOW(), 1)
         GROUP BY tm.name
         HAVING AVG(tm.memory_use) > 0.7"
    then: "warning avg memory: {{.V2}} in server: {{.V1}}"
    else: ""

 pushers: [ telegram ]
 checkeveryseconds: 22
 checkconnservereveryseconds: 42
 dataconnects: /Users/peterkorotkiy/go/src/github.com/darkfoxs96/servermetric/connects-data.cfg

# telegram, email ... Now supported only 'telegram bot'
pushers:
 telegram:
  token: "841563697:AAEDpNQBkNpFSUtae_ZgSRhxKzeJRntdrik"
  data: /Users/peterkorotkiy/go/src/github.com/darkfoxs96/servermetric/telegram-data.cfg

# params for connect to clickhouse
database:
  username: "clickhouse"
  password: "clickhouse"
  database: "default"
  host: "localhost"
  port: "9001"

# create table by metrics
metrics:
  cpu_use:
    ENGINE: MergeTree(event_date, (name), 8192)
    event_date: "Date DEFAULT NOW()"
    event_datetime: "DateTime DEFAULT NOW()"
    cpu_use: "Float64 DEFAULT 0.0"
    name: "String DEFAULT ''"
  memory_use:
    ENGINE: MergeTree(event_date, (name), 8192)
    event_date: "Date DEFAULT NOW()"
    event_datetime: "DateTime DEFAULT NOW()"
    memory_use: "Float64 DEFAULT 0.0"
    name: "String DEFAULT ''"

# server settings
server:
  port: "9082"
  key: "SDDEDpNQBkNpFSUtae_ZgSRhxKzeJRntdrik"
