version: '3'

services:
  database:
    image: yandex/clickhouse-server:19.6.2.11
    ports:
      - 8124:8123
      - 9001:9000
    volumes:
      - /Users/peterkorotkiy/docker/clickhouse/data:/var/lib/clickhouse
      - /Users/peterkorotkiy/docker/clickhouse/log:/var/log/clickhouse-server
      - /Users/peterkorotkiy/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - /Users/peterkorotkiy/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
